In [2]:
import pandas as pd

df = pd.read_csv("/content/drive/MyDrive/tutorials/pokemon_data.csv")

In [ ]:
print(df)

       #                   Name   Type 1  Type 2  HP  Attack  Defense  \
0      1              Bulbasaur    Grass  Poison  45      49       49
1      2                Ivysaur    Grass  Poison  60      62       63
2      3               Venusaur    Grass  Poison  80      82       83
3      3  VenusaurMega Venusaur    Grass  Poison  80     100      123
4      4             Charmander     Fire     NaN  39      52       43
..   ...                    ...      ...     ...  ..     ...      ...
795  719                Diancie     Rock   Fairy  50     100      150
796  719    DiancieMega Diancie     Rock   Fairy  50     160      110
797  720    HoopaHoopa Confined  Psychic   Ghost  80     110       60
798  720     HoopaHoopa Unbound  Psychic    Dark  80     160       60
799  721              Volcanion     Fire   Water  80     110      120

     Sp. Atk  Sp. Def  Speed  Generation  Legendary
0         65       65     45           1      False
1         80       80     60           1      False
2        100      100     80           1      False
3        122      120     80           1      False
4         60       50     65           1      False
..       ...      ...    ...         ...        ...
795      100      150     50           6       True
796      160      110    110           6       True
797      150      130     70           6       True
798      170      130     80           6       True
799      130       90     70           6       True

[800 rows x 12 columns]

In [ ]:
# print(df.head(5))

print(df.tail(5))

       #                 Name   Type 1 Type 2  HP  Attack  Defense  Sp. Atk  \
795  719              Diancie     Rock  Fairy  50     100      150      100
796  719  DiancieMega Diancie     Rock  Fairy  50     160      110      160
797  720  HoopaHoopa Confined  Psychic  Ghost  80     110       60      150
798  720   HoopaHoopa Unbound  Psychic   Dark  80     160       60      170
799  721            Volcanion     Fire  Water  80     110      120      130

     Sp. Def  Speed  Generation  Legendary
795      150     50           6       True
796      110    110           6       True
797      130     70           6       True
798      130     80           6       True
799       90     70           6       True

In [ ]:
print(df[['Name', 'Generation']][0:5])

                    Name  Generation
0              Bulbasaur           1
1                Ivysaur           1
2               Venusaur           1
3  VenusaurMega Venusaur           1
4             Charmander           1

In [ ]:
print(df.head(3))

   #       Name Type 1  Type 2  HP  Attack  Defense  Sp. Atk  Sp. Def  Speed  \
0  1  Bulbasaur  Grass  Poison  45      49       49       65       65     45
1  2    Ivysaur  Grass  Poison  60      62       63       80       80     60
2  3   Venusaur  Grass  Poison  80      82       83      100      100     80

   Generation  Legendary
0           1      False
1           1      False
2           1      False

In [ ]:
print(df.iloc[2,1])

Venusaur

In [ ]:
# x = 0
# while x>=5:
# for index, row in df.iterrows():
#   print(index+1, row[['Name', 'Legendary']])
  # print(type(index))
  # print(type(row))
# x+=1
columnstoprint = ['Name', 'Legendary']
# for cname in columnstoprint:
y=print(df[columnstoprint][0:7])
print(type(y))

                    Name  Legendary
0              Bulbasaur      False
1                Ivysaur      False
2               Venusaur      False
3  VenusaurMega Venusaur      False
4             Charmander      False
5             Charmeleon      False
6              Charizard      False
<class 'NoneType'>

In [ ]:
# df.loc[df['Type 1']=='Fire']
# sel_col = df.loc[:,(df == ['Fire', 'Ice']).any()]
# print(sel_col)
# selected_columns = df.loc[:, (df == 2).any()]

specific_values = ['Fire', 'Ice']

# Create the condition to check for the specific values in each column
condition = df.isin(specific_values)

# Select columns with specific values using loc and boolean indexing
# selected_columns = df.loc[:, condition.any()]
selected_rows = df.loc[condition.any(axis=1)]

print(selected_rows)

       #                       Name Type 1  Type 2   HP  Attack  Defense  \
4      4                 Charmander   Fire     NaN   39      52       43
5      5                 Charmeleon   Fire     NaN   58      64       58
6      6                  Charizard   Fire  Flying   78      84       78
7      6  CharizardMega Charizard X   Fire  Dragon   78     130      111
8      6  CharizardMega Charizard Y   Fire  Flying   78     104       78
..   ...                        ...    ...     ...  ...     ...      ...
768  698                     Amaura   Rock     Ice   77      59       50
769  699                    Aurorus   Rock     Ice  123      77       72
788  712                   Bergmite    Ice     NaN   55      69       85
789  713                    Avalugg    Ice     NaN   95     117      184
799  721                  Volcanion   Fire   Water   80     110      120

     Sp. Atk  Sp. Def  Speed  Generation  Legendary
4         60       50     65           1      False
5         80       65     80           1      False
6        109       85    100           1      False
7        130       85    100           1      False
8        159      115    100           1      False
..       ...      ...    ...         ...        ...
768       67       63     46           6      False
769       99       92     58           6      False
788       32       35     28           6      False
789       44       46     28           6      False
799      130       90     70           6       True

[102 rows x 12 columns]

In [ ]:
value1 = 'Fire'
value2 = 'Rock'

# Create the condition to check for the specified values in the column
# condition = (df['Type 1'] == value1) & (df['Type 2'] == value2)

# Get the rows that satisfy the condition using loc and boolean indexing
selected_rows = df.loc[(df['Type 1'] == value1) & (df['Type 2'] == value2)]

# Print the selected rows
print(selected_rows)

       #      Name Type 1 Type 2  HP  Attack  Defense  Sp. Atk  Sp. Def  \
237  219  Magcargo   Fire   Rock  50      50      120       80       80

     Speed  Generation  Legendary
237     30           2      False

In [ ]:
df.sort_values(['Type 1', '#'])

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
13,10,Caterpie,Bug,NaN,45,30,35,20,20,45,1,False
14,11,Metapod,Bug,NaN,50,20,55,25,25,30,1,False
15,12,Butterfree,Bug,Flying,60,45,50,90,80,70,1,False
16,13,Weedle,Bug,Poison,40,35,30,20,20,50,1,False
17,14,Kakuna,Bug,Poison,45,25,50,25,25,35,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
724,656,Froakie,Water,NaN,41,56,40,62,44,71,6,False
725,657,Frogadier,Water,NaN,54,63,52,83,56,97,6,False
726,658,Greninja,Water,Dark,72,95,67,103,71,122,6,False
762,692,Clauncher,Water,NaN,50,53,62,58,63,44,6,False
763,693,Clawitzer,Water,NaN,71,73,88,120,89,59,6,False

In [ ]:
df.sort_values(['Type 1', '#'], ascending = [1,0])

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
734,666,Vivillon,Bug,Flying,80,52,50,90,50,89,6,False
733,665,Spewpa,Bug,NaN,45,22,60,27,30,29,6,False
732,664,Scatterbug,Bug,NaN,38,35,40,27,25,35,6,False
717,649,Genesect,Bug,Steel,71,120,95,120,95,99,5,False
698,637,Volcarona,Bug,Fire,85,60,65,135,105,100,5,False
...,...,...,...,...,...,...,...,...,...,...,...,...
59,54,Psyduck,Water,NaN,50,52,48,65,50,55,1,False
11,9,Blastoise,Water,NaN,79,83,100,85,105,78,1,False
12,9,BlastoiseMega Blastoise,Water,NaN,79,103,120,135,115,78,1,False
10,8,Wartortle,Water,NaN,59,63,80,65,80,58,1,False
9,7,Squirtle,Water,NaN,44,48,65,50,64,43,1,False

### **Making Changes to the data**

In [4]:
# df['Total'] = df['HP'] + df['Attack'] + df['Defense'] + df['Sp. Atk'] + df['Sp. Def'] + df['Speed']
df['Total'] = df.iloc[:,4:10].sum(axis=1)
df.head(5)

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,318
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,405
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,525
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False,625
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False,309

In [ ]:
df

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,318
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,405
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,525
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False,625
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False,309
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True,600
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True,700
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True,600
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True,680
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True,600

In [ ]:
df.drop(columns='Total')

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

In [ ]:
cols = list(df.columns)
print(cols)
print(len(cols))
df = df[cols[0:10]+[cols[-1]]+cols[10:12]]

['#', 'Name', 'Type 1', 'Type 2', 'HP', 'Attack', 'Defense', 'Sp. Atk', 'Sp. Def', 'Speed', 'Generation', 'Legendary', 'Total']
13

In [ ]:
df
cols = list(df.columns)
print(cols)
print(len(cols))

['#', 'Name', 'Type 1', 'Type 2', 'HP', 'Attack', 'Defense', 'Sp. Atk', 'Sp. Def', 'Speed', 'Total', 'Generation', 'Legendary']
13

In [ ]:
df.head(5)

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Legendary,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,False,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,False,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,False,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,False,1,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,False,1,False

In [ ]:
df.to_csv('modified.csv', index = False)

In [ ]:
df2 = pd.read_csv("/content/modified.csv")
print(df2)

       #                   Name   Type 1  Type 2  HP  Attack  Defense  \
0      1              Bulbasaur    Grass  Poison  45      49       49
1      2                Ivysaur    Grass  Poison  60      62       63
2      3               Venusaur    Grass  Poison  80      82       83
3      3  VenusaurMega Venusaur    Grass  Poison  80     100      123
4      4             Charmander     Fire     NaN  39      52       43
..   ...                    ...      ...     ...  ..     ...      ...
795  719                Diancie     Rock   Fairy  50     100      150
796  719    DiancieMega Diancie     Rock   Fairy  50     160      110
797  720    HoopaHoopa Confined  Psychic   Ghost  80     110       60
798  720     HoopaHoopa Unbound  Psychic    Dark  80     160       60
799  721              Volcanion     Fire   Water  80     110      120

     Sp. Atk  Sp. Def  Speed  Total  Generation  Legendary
0         65       65     45    318           1      False
1         80       80     60    405           1      False
2        100      100     80    525           1      False
3        122      120     80    625           1      False
4         60       50     65    309           1      False
..       ...      ...    ...    ...         ...        ...
795      100      150     50    600           6       True
796      160      110    110    700           6       True
797      150      130     70    600           6       True
798      170      130     80    680           6       True
799      130       90     70    600           6       True

[800 rows x 13 columns]

In [ ]:
df.to_csv('modified.txt', index = False, sep='\t')

In [ ]:
smol_df = df.loc[(df['Type 1']=='Fire') & (df['Type 2']=='Flying')]
smol_df.reset_index(drop=True, inplace=True)
smol_df

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Total,Generation,Legendary
0,6,Charizard,Fire,Flying,78,84,78,109,85,100,534,1,False
1,6,CharizardMega Charizard Y,Fire,Flying,78,104,78,159,115,100,634,1,False
2,146,Moltres,Fire,Flying,90,100,90,125,85,90,580,1,True
3,250,Ho-oh,Fire,Flying,106,130,90,110,154,90,680,2,True
4,662,Fletchinder,Fire,Flying,62,73,55,56,52,84,382,6,False
5,663,Talonflame,Fire,Flying,78,81,71,74,69,126,499,6,False

In [ ]:
import re

df['Status'] = 0
df = df.loc[~df['Name'].str.contains('^Mega[a-z]*')]

In [ ]:
df.loc[df['Total'] >= 550, ['Status']] = 'Good'

df

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total,Status
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,318,0
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,405,0
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,525,0
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False,625,Good
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False,309,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True,600,Good
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True,700,Good
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True,600,Good
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True,680,Good
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True,600,Good

In [ ]:
df.loc[df['Name']=='Yanmega']

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total,Status
520,469,Yanmega,Bug,Flying,86,76,86,116,56,95,4,False,515,0

In [5]:
good_pokemon = df[df['Total']>550]

good_pokemon.head()

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False,625
7,6,CharizardMega Charizard X,Fire,Dragon,78,130,111,130,85,100,1,False,634
8,6,CharizardMega Charizard Y,Fire,Flying,78,104,78,159,115,100,1,False,634
12,9,BlastoiseMega Blastoise,Water,NaN,79,103,120,135,115,78,1,False,630
23,18,PidgeotMega Pidgeot,Normal,Flying,83,80,80,135,80,121,1,False,579

In [13]:
dualtype = df[(df["Type 1"].isin(['Fairy', 'Steel'])) & (df["Type 2"].isin(['Fairy', 'Steel']))]

dualtype.head()

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
328,303,Mawile,Steel,Fairy,50,85,85,55,55,50,3,False,380
329,303,MawileMega Mawile,Steel,Fairy,50,105,125,55,95,50,3,False,480
777,707,Klefki,Steel,Fairy,57,80,91,80,87,75,6,False,470